package com.rentit.sales.domain.model;

public enum POStatus { PENDING, OPEN, REJECTED, CLOSED, PENDING_EXTENSION,
    ACCEPTED, DISPATCHED, DELIVERED, REJECTED_BY_CUSTOMER, RETURNED, INVOICED, CANCELLED}
